=== gitpan/Benchmark-Harness/xsd/BenchmarkHarnessTrace.xsd
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">	<xsd:element name="Trace">		<xsd:complexType>			<xsd:sequence>				<xsd:element name="T" minOccurs="1" maxOccurs="unbounded">					<xsd:complexType>						<xsd:sequence>							<xsd:element name="V" minOccurs="1" maxOccurs="unbounded">								<xsd:complexType>									<xsd:attribute name="n" use="required" type="xsd:string"/>									<xsd:attribute name="t" type="xsd:string"/>								</xsd:complexType>							</xsd:element>						</xsd:sequence>						<xsd:attribute name="t" use="required" type="xsd:float"/>						<xsd:attribute name="p" type="xsd:string"/>						<xsd:attribute name="f" type="xsd:string"/>						<xsd:attribute name="l" use="optional" type="xsd:integer"/>						<xsd:attribute name="ps" use="required" type="xsd:short"/>						<xsd:attribute name="n" type="xsd:string" use="required"/>					</xsd:complexType>				</xsd:element>			</xsd:sequence>			<xsd:attribute name="n" type="xsd:string" use="required"/>			<xsd:attribute name="tm" type="xsd:string" use="required"/>			<xsd:attribute name="pid" type="xsd:short" use="required"/>			<xsd:attribute name="userid" type="xsd:string" use="required"/>			<xsd:attribute name="os" type="xsd:string" use="required"/>		</xsd:complexType>	</xsd:element></xsd:schema>

=== gitpan/Benchmark-Harness/t/benchmarkTrace.xml
<Trace  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='../xsd/BenchmarkHarnessTrace.xsd'><T p='TestServer' l='3' n='Entry(TestServer::Loop)'><V n='1'/><V n='2'/><V n='3'/><V n='4'/></T><T n='Entry(TestServer::Max)'><V n='1'/></T><T l='6' n='Exit(TestServer::Max)'><V n='1'/></T><T l='3' n='Entry(TestServer::Max)'><V n='1'/></T><T l='6' n='Exit(TestServer::Max)'><V n='1'/></T><T l='3' n='Entry(TestServer::Max)'><V n='1'/></T><T l='6' n='Exit(TestServer::Max)'><V n='1'/></T><T l='3' n='Entry(TestServer::Max)'><V n='1'/></T><T l='6' n='Exit(TestServer::Max)'><V n='1'/></T><T l='3' n='Entry(TestServer::Min)'><V n='1'/></T><T l='6' n='Exit(TestServer::Min)'><V n='1'/></T><T l='3' n='Entry(TestServer::Min)'><V n='1'/></T><T l='6' n='Exit(TestServer::Min)'><V n='1'/></T><T l='3' n='Entry(TestServer::Min)'><V n='1'/></T><T l='6' n='Exit(TestServer::Min)'><V n='1'/></T><T l='3' n='Entry(TestServer::Min)'><V n='1'/></T><T l='6' n='Exit(TestServer::Min)'><V n='1'/></T><T n='Exit(TestServer::Loop)'><V n='1'/></T><T n='Exit(TestServer::Loop)'><V n='1'/></T><T l='3' n='Entry(TestServer::Loop)'><V n='1'/><V n='2'/><V n='3'/><V n='4'/></T><T n='Entry(TestServer::Max)'><V n='1'/></T><T l='6' n='Exit(TestServer::Max)'><V n='1'/></T><T l='3' n='Entry(TestServer::Max)'><V n='1'/></T><T l='6' n='Exit(TestServer::Max)'><V n='1'/></T><T l='3' n='Entry(TestServer::Max)'><V n='1'/></T><T l='6' n='Exit(TestServer::Max)'><V n='1'/></T><T l='3' n='Entry(TestServer::Max)'><V n='1'/></T><T l='6' n='Exit(TestServer::Max)'><V n='1'/></T><T l='3' n='Entry(TestServer::Min)'><V n='1'/></T><T l='6' n='Exit(TestServer::Min)'><V n='1'/></T><T l='3' n='Entry(TestServer::Min)'><V n='1'/></T><T l='6' n='Exit(TestServer::Min)'><V n='1'/></T><T l='3' n='Entry(TestServer::Min)'><V n='1'/></T><T l='6' n='Exit(TestServer::Min)'><V n='1'/></T><T l='3' n='Entry(TestServer::Min)'><V n='1'/></T><T l='6' n='Exit(TestServer::Min)'><V n='1'/></T><T l='9' n='Exit(TestServer::Loop)'><V n='1'/><V n='2'/></T></Trace>
