=== gitpan/Benchmark-Harness/xsd/Trace.xsd
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">	<xsd:element name="Trace">		<xsd:complexType>			<xsd:sequence>				<xsd:element name="ID" type="TID" maxOccurs="unbounded"/>				<xsd:element name="T" type="TT" maxOccurs="unbounded"/>			</xsd:sequence>			<xsd:attribute name="n" type="xsd:string" use="required"/>			<xsd:attribute name="v" type="xsd:string" use="required"/>			<xsd:attribute name="V" type="xsd:string" use="required"/>			<xsd:attribute name="tm" type="xsd:string" use="required"/>			<xsd:attribute name="pid" type="xsd:short" use="required"/>			<xsd:attribute name="userid" type="xsd:string" use="required"/>			<xsd:attribute name="os" type="xsd:string" use="required"/>		</xsd:complexType>	</xsd:element>	<xsd:complexType name="TT">		<xsd:attribute name="_i" type="xsd:integer" use="required"/>		<xsd:attribute name="_m" use="required">			<xsd:simpleType>				<xsd:restriction base="xsd:string">					<xsd:enumeration value="E"/>					<xsd:enumeration value="X"/>				</xsd:restriction>			</xsd:simpleType>		</xsd:attribute>		<xsd:attribute name="n" type="xsd:string" use="optional"/>		<xsd:attribute name="m" type="xsd:long" use="required"/>		<xsd:attribute name="t" type="xsd:float" use="required"/>		<xsd:attribute name="u" type="xsd:float" use="optional"/>		<xsd:attribute name="s" type="xsd:float" use="optional"/>		<xsd:attribute name="p" type="xsd:float" use="optional"/>		<xsd:attribute name="x" type="xsd:float" use="optional"/>		<xsd:attribute name="r" type="xsd:string" use="optional"/>		<xsd:attribute name="f" type="xsd:string" use="optional"/>		<xsd:attribute name="l" type="xsd:integer" use="optional"/>	</xsd:complexType>	<xsd:complexType name="TID">		<xsd:attribute name="id" type="xsd:integer" use="required"/>		<xsd:attribute name="type" use="required">			<xsd:simpleType>				<xsd:restriction base="xsd:string">					<xsd:enumeration value="method"/>				</xsd:restriction>			</xsd:simpleType>		</xsd:attribute>		<xsd:attribute name="name" type="xsd:NMTOKEN" use="required"/>		<xsd:attribute name="package" type="xsd:string" use="optional"/>		<xsd:attribute name="modifiers" type="xsd:string" use="optional"/>	</xsd:complexType></xsd:schema>

=== gitpan/Benchmark-Harness/t/benchmark.Trace.xml
<Trace  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='http://schemas.benchmark-harness.org/Trace.xsd' v='1.01' V='1.08'><ID id='0' name='Loop' type='method' package='TestServer' modifiers=''/><ID id='1' name='Max' type='method' package='TestServer' modifiers='0'/><ID id='2' name='Min' type='method' package='TestServer' modifiers='2|1'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/><T _i='0' _m='E'/><T _i='2' _m='E'/><T _i='2' _m='X'/><T _i='0' _m='X'/></Trace>
